#!/usr/bin/env node
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const hash = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
const out = resolve(__dirname, '../client/src/git-hash.ts');
writeFileSync(out, `// Auto-generated by scripts/write-version.js — do not edit by hand.\nexport const GIT_HASH = '${hash}';\n`);
console.log(`wrote git hash ${hash} → client/src/git-hash.ts`);
